version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data greenweez finance from le wagon 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: raw data information on orders, product, revenue
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: raw data on product and purchase price
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null 
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: raw data on order's shipping fee, log and ship cost
        columns:
          - name: orders_id
            description: primary key of te table
            tests:
              - unique 
              - not_null 
          - name: shipping_fee
            description: the price customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/transporter
      - name: int_sales_margin
        tests:
            - unique:
                column_name:  "(orders_id || '-' || products_id)" 
            - not_null:
                column_name:
                  - orders_id
                  - products_id
                  - margin
                  - purchase_cost
                  - date_date
                  - revenue
                  - quantity 
    models:
      - name: stg_raw_product
      - name: stg_raw_sales
      - name: stg_raw_ship
      - name: int_sales_margin
        description: margin calculation per order line / product sale
        columns:
          - name: margin
            description: margin = revenue - purchase_cost
          - name: purchase_cost
            description: purchase_cost = quantity * purchase_price
          - name: int_orders_margin
            description: margin calculation per order
            columns:
              - name: orders_id
                description: primary key
              - name: margin
                description: margin = revenue - purchase_cost
              - name: purchase_cost
                description: purchase_cost = quantity * purchase_price
              - name: date_date
                description: date of the order
              - name: revenue
                description: sum of revenue per order
              - name: quantity
                description: sum of quantity per order
              - name: int_orders_operatiional
                description: operational margin calculation per order
                columns:
                  name: operational_margin
                  description: operational margin = margin + shipping fee - log_cost - ship_cost
              - name: finance_days
                description: finance calculation per days
